sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
    futures: true


exchangeStrategies:
- on: binance
  fib:
    symbol: BTCUSDT
    interval: 15m # x4
    quantity: 0.005


backtest:
  # for testing max draw down (MDD) at 03-12
  # see here for more details
  # https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp
  startTime: "2022-03-18"
  endTime: "2022-03-20"
  symbols:
    - BTCUSDT
  account:
    binance:
      balances:
        BTC: 0.5
        USDT: 30_000.0
